### ISSUE TITLE
Does this still work? 

### ISSUE THREAD

**Issue by mazjindeel** [jabiddle/GlobalPokerExt#2]
I have tried to run this extension as of today, and it doesn't seem to be working. Can you confirm if it is still working for you as of March 2019? 

Thanks

**Comment by nachishankar** [comment]
Hey maz, 
It works, but you have to change a couple of things in the manifest.json file. Are you planning on working on this ?

**Comment by mazjindeel** [comment]
Yes, I have a project in mind for global, and as part of it I would most likely be doing bug fixes and possibly implementing new features for this project. 

What changes have to be made on the manifest file?

**Comment by mazjindeel** [comment]
Ah, thanks for the hint - I was able to modify the manifest.json and get it working. Thanks for the direction!

**Comment by nachishankar** [comment]
Hey Sorry, I didn't see this. Glad you got it to work. Could you pm me at nachishankar@gmail.com I would also like to work on this - but I am not really a programmer. Just know bits and pieces
